name: Test

on:
  pull_request_target:
    types: [labeled]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Test Suite
    runs-on: ubuntu-latest
    if: github.event.label.name == 'run-tests'
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: davidB/rust-cargo-make@v1

      - uses: Swatinem/rust-cache@v2

      - name: Install libsasl2-dev
        run: sudo apt-get install libsasl2-dev

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Check formatting
        run: cargo make format

      - name: Clippy check
        run: cargo make lint

      - name: Run Unit Tests
        run: cargo make cov-ci
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
